{{- if .Values.sshKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp-server.fullname" . }}-ssh-keys
  labels:
    {{- include "sftp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.sshKeys }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}